#!/usr/bin/env python3
"""SAOS artefact manifest generator.

Walks the artefact set and writes MANIFEST.csv and MANIFEST.md with, for every
file: relative path, size in bytes, SHA-256, category, role and provenance.

Also performs two integrity checks and records the result:
  1. Every .xlsx is loaded twice (formulas and data_only). A workbook whose
     Dashboard tile B5 is None has no cached formula values and will read as
     blank in any previewer, in pandas and in automated report generation.
  2. Every .docx opens and reports its paragraph and table count.

Usage:
  python build_manifest.py [--root PATH] [--out DIR]
"""
import argparse
import csv
import datetime
import hashlib
import os
import sys
import zipfile

CATEGORIES = [
    ('01-governance', 'Governance', 'Process and control documents for the artefact set'),
    ('02-methodology', 'Methodology', 'How SAOS scores, rates and reports'),
    ('03-library', 'Library', 'Machine-readable control catalogue, schema and tooling'),
    ('04-workflows', 'Workflows', 'Operational procedures for running an engagement'),
    ('05-deliverables', 'Deliverables', 'Client-facing files'),
    ('06-source', 'Source', 'Buildable source project (YAML library and generators)'),
    ('07-reference', 'Reference', 'Format guidance, QA findings and framework notes'),
    ('08-infrastructure', 'Infrastructure', 'Dependency manifests and build instructions'),
]

ROLES = {
    '.md': 'Documentation',
    '.yaml': 'Canonical source - control library',
    '.yml': 'Canonical source - control library',
    '.py': 'Build or tooling script',
    '.js': 'Build script',
    '.json': 'Machine-readable data or schema',
    '.csv': 'Machine-readable export',
    '.xlsx': 'Excel workbook',
    '.docx': 'Word document',
    '.txt': 'Dependency manifest',
}

PROVENANCE = {
    '05-deliverables/SAOS-Assessment-Workbook-v0.1-BLANK.xlsx':
        'Original blank engagement workbook, renamed to the naming convention. Rebuild stamp 2025-11-28 predates the current toolchain - rebuild before issue, see QA finding F-02.',
    '05-deliverables/SAOS-Assessment-Workbook-v0.1-SAMPLE.xlsx':
        'Generated by build_workbook.py --sample, then recalculated in Excel. Sample mode writes every identifying field as "Redacted" so the build can never emit a plausible client identity. Never issue as a client deliverable - see QA finding F-01.',
    '05-deliverables/SAOS-Executive-Report-Template-v0.1.docx':
        'Original Word report template; version added to the filename.',
    '06-source/README.md': 'Copied from the original source README; updated for the --sample flag.',
    '06-source/build/build_workbook.py': 'Copied from the original source; the synthetic-data flag was renamed to --sample and every sample-mode identity field is now written as Redacted.',
    '06-source/build/build_report.js': 'Copied from the original source.',
    '06-source/library/meta.yaml': 'Copied from the original source.',
    '08-infrastructure/package.json': 'Authored for this packaging; not present in the original delivery (QA finding F-03).',
    '08-infrastructure/package-lock.json': 'Authored for this packaging; not present in the original delivery (QA finding F-03).',
    '08-infrastructure/requirements.txt': 'Authored for this packaging; not present in the original delivery (QA finding F-03).',
}

GENERATED = {
    '03-library/control-catalogue.csv', '03-library/control-catalogue.json',
    '03-library/control-evidence.csv', '03-library/domain-registry.csv',
    '03-library/family-registry.csv', '03-library/framework-mapping.csv',
}


def sha256(path):
    h = hashlib.sha256()
    with open(path, 'rb') as fh:
        for chunk in iter(lambda: fh.read(65536), b''):
            h.update(chunk)
    return h.hexdigest()


def category_of(rel):
    top = rel.split(os.sep)[0] if os.sep in rel else ''
    for prefix, name, _ in CATEGORIES:
        if rel.startswith(prefix):
            return name
    return 'Root' if top in ('', '.') else top


def check_xlsx(path):
    try:
        import openpyxl
    except ImportError:
        return 'not checked (openpyxl not installed)'
    try:
        wbf = openpyxl.load_workbook(path, data_only=False, read_only=False)
        wbv = openpyxl.load_workbook(path, data_only=True, read_only=False)
    except Exception as e:
        return f'UNREADABLE: {e}'
    parts = []
    parts.append(f'{len(wbf.sheetnames)} sheets')
    if 'Dashboard' in wbv.sheetnames:
        v = wbv['Dashboard']['B5'].value
        if v is None:
            parts.append('NO CACHED VALUES - recalculate before distributing')
        else:
            try:
                parts.append(f'cached Dashboard!B5={v:.2f}')
            except (TypeError, ValueError):
                parts.append(f'cached Dashboard!B5={v}')
    else:
        parts.append('no Dashboard sheet')
    try:
        z = zipfile.ZipFile(path)
        parts.append('calcChain present' if any('calcChain' in n for n in z.namelist()) else 'no calcChain')
    except Exception:
        pass
    return '; '.join(parts)


def check_docx(path):
    try:
        import docx
    except ImportError:
        return 'not checked (python-docx not installed)'
    try:
        d = docx.Document(path)
        return f'{len(d.paragraphs)} paragraphs, {len(d.tables)} tables'
    except Exception as e:
        return f'UNREADABLE: {e}'


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    ap = argparse.ArgumentParser()
    ap.add_argument('--root', default=os.path.dirname(here))
    ap.add_argument('--out', default=os.path.dirname(here))
    args = ap.parse_args()
    root = os.path.abspath(args.root)
    out = os.path.abspath(args.out)

    rows = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = sorted(d for d in dirnames if d not in ('node_modules', '__pycache__', '.git'))
        for fn in sorted(filenames):
            full = os.path.join(dirpath, fn)
            rel = os.path.relpath(full, root).replace('\\', '/')
            if rel in ('MANIFEST.csv', 'MANIFEST.md'):
                continue
            ext = os.path.splitext(fn)[1].lower()
            if ext not in ROLES:
                continue
            note = PROVENANCE.get(rel, 'Regenerated from the YAML library by export_library.py' if rel in GENERATED
                                  else 'Authored for this documentation and tooling packaging')
            if ext == '.xlsx':
                note += ' | ' + check_xlsx(full)
            elif ext == '.docx':
                note += ' | ' + check_docx(full)
            rows.append({
                'path': rel,
                'category': category_of(rel),
                'role': ROLES[ext],
                'bytes': os.path.getsize(full),
                'sha256': sha256(full),
                'provenance': note,
            })

    rows.sort(key=lambda r: (r['category'], r['path']))
    total = sum(r['bytes'] for r in rows)
    stamp = datetime.date.today().isoformat()

    csv_path = os.path.join(out, 'MANIFEST.csv')
    with open(csv_path, 'w', newline='', encoding='utf-8-sig') as fh:
        w = csv.DictWriter(fh, fieldnames=['path', 'category', 'role', 'bytes', 'sha256', 'provenance'])
        w.writeheader()
        w.writerows(rows)

    by_cat = {}
    for r in rows:
        by_cat.setdefault(r['category'], []).append(r)
    by_ext = {}
    for r in rows:
        e = os.path.splitext(r['path'])[1].lower()
        by_ext[e] = by_ext.get(e, 0) + 1

    md = []
    md.append('# Manifest')
    md.append('')
    md.append('Every file in `artefacts/`, with size, SHA-256 and provenance. Generated by')
    md.append('`08-infrastructure/build_manifest.py`. Regenerate after any change.')
    md.append('')
    md.append('| | |')
    md.append('|---|---|')
    md.append(f'| Generated | {stamp} |')
    md.append(f'| Files | {len(rows)} |')
    md.append(f'| Total size | {total / 1024:.1f} KB |')
    md.append(f'| Categories | {len(by_cat)} |')
    md.append(f'| Source library | `06-source/library/` — 60 controls, SHA-256 below |')
    md.append('')
    md.append('## Verify integrity')
    md.append('')
    md.append('```powershell')
    md.append('# Compare every file against this manifest')
    md.append('Get-Content MANIFEST.csv | ConvertFrom-Csv | ForEach-Object {')
    md.append('    $p = Join-Path $PWD $_.path')
    md.append('    if (-not (Test-Path $p)) { "MISSING  $($_.path)"; return }')
    md.append('    $h = (Get-FileHash $p -Algorithm SHA256).Hash.ToLower()')
    md.append('    if ($h -eq $_.sha256) { "OK       $($_.path)" } else { "CHANGED  $($_.path)" }')
    md.append('}')
    md.append('```')
    md.append('')
    md.append('A `CHANGED` line on a delivered file means it is no longer the artefact that was')
    md.append('reviewed. A `MISSING` line means the set is incomplete.')
    md.append('')
    md.append('## By category')
    md.append('')
    order = [name for _, name, _ in CATEGORIES] + ['Root']
    for name in order:
        items = by_cat.get(name)
        if not items:
            continue
        size = sum(i['bytes'] for i in items)
        md.append(f'### {name} — {len(items)} files, {size / 1024:.1f} KB')
        md.append('')
        desc = next((d for p, n, d in CATEGORIES if n == name), '')
        if desc:
            md.append(f'{desc}.')
            md.append('')
        md.append('| File | Role | Bytes | SHA-256 (first 16) |')
        md.append('|---|---|---:|---|')
        for i in items:
            md.append(f'| [`{i["path"]}`]({i["path"].replace(" ", "%20")}) | {i["role"]} | {i["bytes"]:,} | `{i["sha256"][:16]}` |')
        md.append('')

    md.append('## Integrity and provenance notes')
    md.append('')
    md.append('| File | Note |')
    md.append('|---|---|')
    for r in rows:
        if r['path'] in PROVENANCE or 'RECALCULATE' in r['provenance'].upper() or r['provenance'] != 'Authored for this documentation and tooling packaging':
            note = r['provenance'].replace('|', '\\|')
            md.append(f'| `{r["path"]}` | {note} |')
    md.append('')
    md.append('## File types')
    md.append('')
    md.append('| Extension | Count | Role |')
    md.append('|---|---:|---|')
    for e in sorted(by_ext, key=lambda x: -by_ext[x]):
        md.append(f'| `{e}` | {by_ext[e]} | {ROLES[e]} |')
    md.append('')
    md.append('## Canonical source')
    md.append('')
    md.append('The control library in `06-source/library/` is the source of truth. Everything')
    md.append('marked *generated* above is produced from it by `build/build_workbook.py` or')
    md.append('`03-library/export_library.py`. Never edit generated files — edit the YAML and')
    md.append('rebuild. `control-catalogue.json` additionally embeds the SHA-256 of each source')
    md.append('YAML file, so any catalogue export is traceable to the exact library snapshot that')
    md.append('produced it.')
    md.append('')

    with open(os.path.join(out, 'MANIFEST.md'), 'w', encoding='utf-8') as fh:
        fh.write('\n'.join(md))

    warn = [r for r in rows if 'NO CACHED VALUES' in r['provenance'] or 'UNREADABLE' in r['provenance']]
    print(f'files       : {len(rows)}')
    print(f'total size  : {total / 1024:.1f} KB')
    print(f'categories  : {len(by_cat)}')
    print(f'written     : {csv_path}')
    print(f'              {os.path.join(out, "MANIFEST.md")}')
    if warn:
        print('\nWARNINGS:')
        for w_ in warn:
            print(f'  ! {w_["path"]}: {w_["provenance"].split("|")[-1].strip()}')
        return 1
    print('integrity   : all workbooks carry cached values; all documents readable')
    return 0


if __name__ == '__main__':
    sys.exit(main())